### ISSUE TITLE
How do I use the Listener?

### ISSUE THREAD

**Issue by ebbeknudsen** [beraybentesen/glide-xamarin-android#1]
How do I use `.Listener()`? I tried creating a class implementing `IRequestListener`, but that interface wants me to implement the property `IntPtr Handle { get; }`

Som help would be appreciated 👍 ;

**Comment by roubachof** [comment]
https://developer.xamarin.com/guides/android/advanced_topics/java_integration_overview/android_callable_wrappers/

**Comment by ebbeknudsen** [comment]
Wow - so simple. Thanks a lot, especially for the quick response :).

You can close this issue now.
