### ISSUE TITLE
Glide 4 errors

### ISSUE THREAD

**Issue by assuncaojr** [beraybentesen/glide-xamarin-android#11]
Glide 4 not work and display many errors:

1.  error: package com.bumptech.glide.load.engine.cache.MemoryCache does not exist		com.bumptech.glide.load.engine.cache.MemoryCache.ResourceRemovedListener
 javac
2. error: package com.bumptech.glide.load.engine does not exist public void onResourceRemoved (com.bumptech.glide.load.engine.Resource p0)
3. package com.bumptech.glide.load.engine does not exist
4. error: package com.bumptech.glide.manager.ConnectivityMonitor does not exist]
5. error: package com.bumptech.glide.manager does not exist
6. error: package com.bumptech.glide.request does not exist
7. error: package com.bumptech.glide.load.engine does not exist
8. error: package com.bumptech.glide.request.target does not exist
9. error: package com.bumptech.glide.load.engine does not exist
[...]

**Comment by beraybentesen** [comment]
Check version 4.1.1 from [NuGet](https://www.nuget.org/packages/Glide.Xamarin/4.1.1)

**Comment by assuncaojr** [comment]
Thank's
