### ISSUE TITLE
Can't find Signature 

### ISSUE THREAD

**Issue by ghost** [beraybentesen/glide-xamarin-android#12]
In Glide 4 I can't find the Signature method anymore.

My code looks like this (working with Glide 3.8):

  Glide.With(_parentActivity)
                 .Load($"{KeyValueStore.HttpImageUri}category_{category.Code}.jpg")
                 .Signature(new StringSignature(category.ImageLastModified.HasValue ? category.ImageLastModified.Value.ToString("yyyy-MM-ddTHH:mm:ss") : string.Empty))
                 .Into(viewHolder.CategoryImage);

Has the Signature method been removed in version 4?

**Comment by beraybentesen** [comment]
You can check [documentation](http://bumptech.github.io/glide/doc/options.html). I think it's been removed.
