### ISSUE TITLE
Glide 4.0

### ISSUE THREAD

**Issue by nickelnext** [beraybentesen/glide-xamarin-android#7]
Hello sir

Do you have any idea when you are gonna bind V.4.00 RC?

The new release has some interesting features (like the loading only from cache .onlyRetrieveFromCache(true) method which is vital sometimes)
I tried to bind it myself based on your transforms but i am not that skilled in this binding stuff and i couldn't do it

Thank you for the great job so far!

**Comment by beraybentesen** [comment]
I am not sure if Xamarin Android will be able to support further updates since Glide 4.00 RC requires annotation processor : " annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1' ". 
I will be following them to be able to create a new package.

**Comment by nickelnext** [comment]
Thanks for the reply.

I'll be looking forward any kind of updates.

Cheers

**Comment by hegelsu** [comment]
4.0 release is update.
